server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC
    password: 123456
    username: root
    filer: wall,stat
    dbcp2:
      max-idle: 10
      min-idle: 5
      max-wait-millis: 10000
      initial-size: 5

  #thymeleaf模板引擎
  thymeleaf:
    cache: false

  #文件上传相关设置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis-plus:
  type-aliases-package: cn.tycoding.biz.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    banner: false
